Document: thc-ssl-dos
Title: Debian thc-ssl-dos Manual
Author: <insert document author here>
Abstract: This manual describes what thc-ssl-dos is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/thc-ssl-dos/thc-ssl-dos.sgml.gz

Format: postscript
Files: /usr/share/doc/thc-ssl-dos/thc-ssl-dos.ps.gz

Format: text
Files: /usr/share/doc/thc-ssl-dos/thc-ssl-dos.text.gz

Format: HTML
Index: /usr/share/doc/thc-ssl-dos/html/index.html
Files: /usr/share/doc/thc-ssl-dos/html/*.html
